<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.5-dev (doctrine2-annotation) on 2015-01-20 12:50:59.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Bap\Bundle\IssueBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Bap\Bundle\IssueBundle\Entity\Issue
 *
 * @ORM\Entity(repositoryClass="Entity\Repository\IssueRepository")
 * @ORM\Table(name="bap_issue", indexes={@ORM\Index(name="index2", columns={"summary"}), @ORM\Index(name="index3", columns={"code"}), @ORM\Index(name="index4", columns={"description"}), @ORM\Index(name="index5", columns={"`type`"}), @ORM\Index(name="index6", columns={"priority"}), @ORM\Index(name="index7", columns={"`status`"}), @ORM\Index(name="index8", columns={"tags_id"}), @ORM\Index(name="index9", columns={"reporter_id"}), @ORM\Index(name="index10", columns={"parent_id"}), @ORM\Index(name="index12", columns={"resolution"}), @ORM\Index(name="index13", columns={"assignee_id"})})
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"base"="BaseIssue", "extended"="Issue"})
 */
abstract class BaseIssue
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $parent_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $reporter_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $assignee_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $tags_id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $code;

    /**
     * @ORM\Column(name="`status`", type="string", length=32)
     */
    protected $status;

    /**
     * @ORM\Column(name="`type`", type="string", length=32)
     */
    protected $type;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $summary;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $description;

    /**
     * @ORM\Column(type="string", length=32)
     */
    protected $priority;

    /**
     * @ORM\Column(type="string", length=32)
     */
    protected $resolution;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="IssueCollaborator", mappedBy="issue")
     * @ORM\JoinColumn(name="id", referencedColumnName="issue_id")
     */
    protected $issueCollaborators;

    /**
     * @ORM\OneToMany(targetEntity="IssueRelation", mappedBy="issueRelatedByIssueId")
     * @ORM\JoinColumn(name="id", referencedColumnName="issue_id", onDelete="CASCADE")
     */
    protected $issueRelationRelatedByIssueIds;

    /**
     * @ORM\OneToMany(targetEntity="IssueRelation", mappedBy="issueRelatedByRelatedIssueId")
     * @ORM\JoinColumn(name="id", referencedColumnName="related_issue_id", onDelete="CASCADE")
     */
    protected $issueRelationRelatedByRelatedIssueIds;

    /**
     * @ORM\ManyToOne(targetEntity="IssueType", inversedBy="issues")
     * @ORM\JoinColumn(name="`type`", referencedColumnName="`value`")
     */
    protected $issueType;

    /**
     * @ORM\ManyToOne(targetEntity="IssuePriority", inversedBy="issues")
     * @ORM\JoinColumn(name="priority", referencedColumnName="`value`")
     */
    protected $issuePriority;

    /**
     * @ORM\ManyToOne(targetEntity="IssueResolution", inversedBy="issues")
     * @ORM\JoinColumn(name="resolution", referencedColumnName="`value`")
     */
    protected $issueResolution;
}