<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.5-dev (doctrine2-annotation) on 2015-01-20 12:50:59.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Bap\Bundle\IssueBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Bap\Bundle\IssueBundle\Entity\IssueCollaborator
 *
 * @ORM\Entity(repositoryClass="Entity\Repository\IssueCollaboratorRepository")
 * @ORM\Table(
 *      name="bap_issue_collaborators",
 *      indexes={
 *          @ORM\Index(name="index2", columns={"issue_id"}),
 *          @ORM\Index(name="index3", columns={"user_id"})
 *      }
 * )
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"base"="BaseIssueCollaborator", "extended"="IssueCollaborator"})
 */
abstract class BaseIssueCollaborator
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $issue_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $user_id;

    /**
     * @ORM\ManyToOne(targetEntity="Issue", inversedBy="issueCollaborators")
     * @ORM\JoinColumn(name="issue_id", referencedColumnName="id", nullable=true)
     */
    protected $issue;
}