<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.5-dev (doctrine2-annotation) on 2015-01-20 12:50:59.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Bap\Bundle\IssueBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Bap\Bundle\IssueBundle\Entity\BaseIssueCollaborator;

/**
 * Bap\Bundle\IssueBundle\Entity\BapIssueCollaborator
 *
 * @ORM\Entity(repositoryClass="Entity\Repository\BapIssueCollaboratorRepository")
 */
class IssueCollaborator extends BaseIssueCollaborator
{
}