<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.5-dev (doctrine2-annotation) on 2015-01-20 12:50:59.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Bap\Bundle\IssueBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Bap\Bundle\IssueBundle\Entity\IssueCollaborator
 *
 * @ORM\Entity(repositoryClass="Entity\Repository\IssueCollaboratorRepository")
 * @ORM\Table(
 *      name="bap_issue_collaborators",
 *      indexes={
 *          @ORM\Index(name="index2", columns={"issue_id"}),
 *          @ORM\Index(name="index3", columns={"user_id"})
 *      }
 * )
 * @ORM\Entity(repositoryClass="Entity\Repository\BapIssueCollaboratorRepository")
 */
class IssueCollaborator
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $issue_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $user_id;

    /**
     * @ORM\ManyToOne(targetEntity="Issue", inversedBy="issueCollaborators")
     * @ORM\JoinColumn(name="issue_id", referencedColumnName="id", nullable=true)
     */
    protected $issue;

    /**
     * Issue table real name
     */
    const TABLE_NAME = 'bap_issue_collaborator';

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of issue_id.
     *
     * @param integer $issue_id
     * @return \Bap\Bundle\IssueBundle\Entity\IssueCollaborator
     */
    public function setIssueId($issue_id)
    {
        $this->issue_id = $issue_id;

        return $this;
    }

    /**
     * Get the value of issue_id.
     *
     * @return integer
     */
    public function getIssueId()
    {
        return $this->issue_id;
    }

    /**
     * Set the value of user_id.
     *
     * @param integer $user_id
     * @return \Bap\Bundle\IssueBundle\Entity\IssueCollaborator
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * Get the value of user_id.
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Set Issue entity (many to one).
     *
     * @param \Bap\Bundle\IssueBundle\Entity\Issue $issue
     * @return \Bap\Bundle\IssueBundle\Entity\IssueCollaborator
     */
    public function setIssue(Issue $issue = null)
    {
        $this->issue = $issue;

        return $this;
    }

    /**
     * Get Issue entity (many to one).
     *
     * @return \Bap\Bundle\IssueBundle\Entity\Issue
     */
    public function getIssue()
    {
        return $this->issue;
    }

    public function __sleep()
    {
        return array('id', 'issue_id', 'user_id');
    }
}