placeholders:
    view_navButtons_before:
        items:
            createIssueButton: ~
    view_content_data_additional_information:
        items:
            userIssues: ~

items:
    createIssueButton:
        template: AcademicBtsBundle:Issue:createIssueButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
    userIssues:
        template: AcademicBtsBundle:Issue:userIssues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)