imports:
    - { resource: 'parameters.yml' }

services:
    bap.issue.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "bap.issue.form"
            - "bap.issue"

    bap.issue.form.type:
        class: %bap.issue.form.type.class%
        arguments:
            - @translator
        tags:
            - { name: form.type, alias: bap.issue }

    bap.issue.form.handler:
        class: %bap.issue.form.handler.class%
        scope: request
        arguments:
            - @bap.issue.form
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    bap.issue.form.priority:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "bap_priority_form"
            - "bap_priority"

    bap.issue.form.type.priority:
        class: %bap.issue.form.priority.class%
        tags:
            - { name: form.type, alias: bap_priority }

    bap.issue.form.handler.priority:
        class: %bap.issue.form.handler.class%
        scope: request
        arguments:
            - @bap.issue.form.priority
            - @request
            - @doctrine.orm.entity_manager

    bap.issue.form.resolution:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "bap_resolution_form"
            - "bap_resolution"

    bap.issue.form.type.resolution:
        class: %bap.issue.form.type.class%
        tags:
            - { name: form.type, alias: bap_resolution }

    bap.issue.form.handler.resolution:
        class: %bap.issue.form.resolution.handler.class%
        scope: request
        arguments:
            - @bap.issue.form.resolution
            - @request
            - @doctrine.orm.entity_manager

    bap.issue.issue.manager.api:
        class: %bap.issue.soap.api.manager.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %bap.issue.entity.class%
            - @doctrine.orm.entity_manager

    bap.issue.form.type.issue.api:
        class: %bap.issue.form.type.class%
        arguments:
            - @translator
        tags:
            - { name: form.type, alias: issue }

    bap.issue.form.issue.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["issue", "issue", null]

    bap.issue.form.handler.issue.api:
        class: %bap.issue.form.handler.class%
        scope: request
        arguments:
            - @bap.issue.form.issue.api
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    bap.issue.priority.manager.api:
        class: %bap.issue.soap.api.manager.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %bap.issue.priority.entity.class%
            - @doctrine.orm.entity_manager

    bap.issue.form.priority.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["priority", "priority", null]

    bap.issue.form.handler.priority.api:
        class: %bap.issue.form.handler.class%
        scope: request
        arguments:
            - @bap.issue.form.priority.api
            - @request
            - @doctrine.orm.entity_manager

    bap.issue.resolution.manager.api:
        class: %bap.issue.soap.api.resolution.manager.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %bap.issue.resolution.entity.class%
            - @doctrine.orm.entity_manager

    bap.issue.form.resolution.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["resolution", "resolution", null]

    bap.issue.form.handler.resolution.api:
        class: %bap.issue.form.resolution.handler.class%
        scope: request
        arguments:
            - @bap.issue.form.resolution.api
            - @request
            - @doctrine.orm.entity_manager

    bap.issue.helper.issue_helper:
        class: %bap.issue.helper.class%
        arguments:
            - @translator

    bap.issue.grid.formatter.issue_type_property:
        class: %bap.issue.grid.type.formatter.class%
        arguments:
            - %bap.issue.helper.class%
        tags:
            - { name:  oro_datagrid.extension.formatter.property, type: issue_type }

    bap.issue.twig.extension.issue:
        class: %bap.issue.twig.extension.class%
        arguments:
            - @bap.issue.helper.issue_helper
        tags:
            - { name: twig.extension }
