parameters:
    bap.issue.entity.class: Bap\Bundle\IssueBundle\Entity\Issue
    bap.priority.entity.class: Bap\Bundle\IssueBundle\Entity\Priority
    bap.resolution.entity.class: Bap\Bundle\IssueBundle\Entity\Resolution

    bap.form.type.priority.class: Bap\Bundle\IssueBundle\Form\Type\PriorityType
    bap.form.handler.priority.class: Bap\Bundle\IssueBundle\Form\Handler\PriorityHandler

    bap.form.type.resolution.class: Bap\Bundle\IssueBundle\Form\Type\ResolutionType
    bap.form.handler.resolution.class: Bap\Bundle\IssueBundle\Form\Handler\ResolutionHandler

    bap.form.type.issue.class: Bap\Bundle\IssueBundle\Form\Type\IssueType
    bap.form.handler.issue.class: Bap\Bundle\IssueBundle\Form\Handler\IssueHandler

    bap.priority.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    bap.resolution.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    bap.issue.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    bap.form.type.issue.api.class: Bap\Bundle\IssueBundle\Form\Type\IssueApiType

    bap.helper.issue_helper.class: Bap\Bundle\IssueBundle\Helper\IssueHelper
    bap.grid.formatter.issue_type_property.class: Bap\Bundle\IssueBundle\Grid\Formatter\IssueTypeProperty

    bap.twig.extension.issue.class: Bap\Bundle\IssueBundle\Twig\IssueExtension


services:
    bap.form.issue:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "bap_issue_form"
            - "bap_issue"

    bap.form.type.issue:
        class: %bap.form.type.issue.class%
        arguments:
            - @translator
        tags:
            - { name: form.type, alias: bap_issue }

    bap.form.handler.issue:
        class: %bap.form.handler.issue.class%
        scope: request
        arguments:
            - @bap.form.issue
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    bap.form.priority:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "bap_priority_form"
            - "bap_priority"

    bap.form.type.priority:
        class: %bap.form.type.priority.class%
        tags:
            - { name: form.type, alias: bap_priority }

    bap.form.handler.priority:
        class: %bap.form.handler.priority.class%
        scope: request
        arguments:
            - @bap.form.priority
            - @request
            - @doctrine.orm.entity_manager

    bap.form.resolution:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "bap_resolution_form"
            - "bap_resolution"

    bap.form.type.resolution:
        class: %bap.form.type.resolution.class%
        tags:
            - { name: form.type, alias: bap_resolution }

    bap.form.handler.resolution:
        class: %bap.form.handler.resolution.class%
        scope: request
        arguments:
            - @bap.form.resolution
            - @request
            - @doctrine.orm.entity_manager

    bap.issue.manager.api:
        class: %bap.issue.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %bap.issue.entity.class%
            - @doctrine.orm.entity_manager

    bap.form.type.issue.api:
        class: %bap.form.type.issue.api.class%
        arguments:
            - @translator
        tags:
            - { name: form.type, alias: issue }

    bap.form.issue.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["issue", "issue", null]

    bap.form.handler.issue.api:
        class: %bap.form.handler.issue.class%
        scope: request
        arguments:
            - @bap.form.issue.api
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    bap.priority.manager.api:
        class: %bap.priority.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %bap.priority.entity.class%
            - @doctrine.orm.entity_manager

    bap.form.priority.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["priority", "priority", null]

    bap.form.handler.priority.api:
        class: %bap.form.handler.priority.class%
        scope: request
        arguments:
            - @bap.form.priority.api
            - @request
            - @doctrine.orm.entity_manager

    bap.resolution.manager.api:
        class: %bap.resolution.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %bap.resolution.entity.class%
            - @doctrine.orm.entity_manager

    bap.form.resolution.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["resolution", "resolution", null]

    bap.form.handler.resolution.api:
        class: %bap.form.handler.resolution.class%
        scope: request
        arguments:
            - @bap.form.resolution.api
            - @request
            - @doctrine.orm.entity_manager

    bap.helper.issue_helper:
        class: %bap.helper.issue_helper.class%
        arguments:
            - @translator

    bap.grid.formatter.issue_type_property:
        class: %bap.grid.formatter.issue_type_property.class%
        arguments:
            - @bap.helper.issue_helper
        tags:
            - { name:  oro_datagrid.extension.formatter.property, type: issue_type }

    bap.twig.extension.issue:
        class: %bap.twig.extension.issue.class%
        arguments:
            - @bap.helper.issue_helper
        tags:
            - { name: twig.extension }
