Bap\Bundle\IssueBundle\Entity\Issue:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
    properties:
        code:
            - NotBlank:     ~
            - Length:
                max:        15
        summary:
            - NotBlank:     ~
            - Length:
                max:        200
        type:
            - Choice:
                choices:    [task, story, sub_task, bug]
        reporter:
            - NotBlank:      ~
        createdAt:
            - DateTime:      ~
        updatedAt:
            - DateTime:      ~

Bap\Bundle\IssueBundle\Entity\IssuePriority:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: value
    properties:
        name:
            - NotBlank:     ~
            - Length:
                max:        50
        value:
            - NotBlank:     ~
            - Type:
                type: integer

Bap\Bundle\IssueBundle\Entity\IssueResolution:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: value
    properties:
        value:
            - NotBlank:     ~
            - Length:
                max:        50
