bap_bundle:
    resource:     "@BapIssueBundle/Controller"
    type:         annotation
    prefix:       /bap_

bap_api:
    resource:     "@AcademicBtsBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
