bts_issue_api:
    resource:     "@AcademicBtsBundle/Controller/Api/Rest/IssueController.php"
    type:         rest

bts_priority_api:
    resource:     "@AcademicBtsBundle/Controller/Api/Rest/PriorityController.php"
    type:         rest

bts_resolution_api:
    resource:     "@AcademicBtsBundle/Controller/Api/Rest/ResolutionController.php"
    type:         rest
