<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.5-dev (doctrine2-annotation) on 2015-01-15 07:55:10.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Ezi\Bundle\IssueBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Ezi\Bundle\IssueBundle\Entity\EziIssueType
 *
 * @ORM\Entity(repositoryClass="EntityRepository\EziIssueTypeRepository")
 * @ORM\Table(name="ezi_issue_type", uniqueConstraints={@ORM\UniqueConstraint(name="type_UNIQUE", columns={"`name`"})})
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"base"="BaseEziIssueType", "extended"="EziIssueType"})
 */
class BaseEziIssueType
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="`name`", type="string", length=32)
     */
    protected $name;

    /**
     * @ORM\OneToMany(targetEntity="EziIssue", mappedBy="eziIssueType")
     * @ORM\JoinColumn(name="`name`", referencedColumnName="`type`")
     */
    protected $eziIssues;

    public function __construct()
    {
        $this->eziIssues = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssueType
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssueType
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Add EziIssue entity to collection (one to many).
     *
     * @param \Ezi\Bundle\IssueBundle\Entity\EziIssue $eziIssue
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssueType
     */
    public function addEziIssue(EziIssue $eziIssue)
    {
        $this->eziIssues[] = $eziIssue;

        return $this;
    }

    /**
     * Remove EziIssue entity from collection (one to many).
     *
     * @param \Ezi\Bundle\IssueBundle\Entity\EziIssue $eziIssue
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssueType
     */
    public function removeEziIssue(EziIssue $eziIssue)
    {
        $this->eziIssues->removeElement($eziIssue);

        return $this;
    }

    /**
     * Get EziIssue entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEziIssues()
    {
        return $this->eziIssues;
    }

    public function __sleep()
    {
        return array('id', 'name');
    }
}