<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.5-dev (doctrine2-annotation) on 2015-01-15 07:55:10.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Ezi\Bundle\IssueBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Ezi\Bundle\IssueBundle\Entity\EziIssueRelation
 *
 * @ORM\Entity(repositoryClass="EntityRepository\EziIssueRelationRepository")
 * @ORM\Table(name="ezi_issue_relations", indexes={@ORM\Index(name="index2", columns={"issue_id"}), @ORM\Index(name="index3", columns={"linked_issue_id"})})
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"base"="BaseEziIssueRelation", "extended"="EziIssueRelation"})
 */
class BaseEziIssueRelation
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $issue_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $linked_issue_id;

    /**
     * @ORM\ManyToOne(targetEntity="EziIssue", inversedBy="eziIssueRelationRelatedByIssueIds")
     * @ORM\JoinColumn(name="issue_id", referencedColumnName="id")
     */
    protected $eziIssueRelatedByIssueId;

    /**
     * @ORM\ManyToOne(targetEntity="EziIssue", inversedBy="eziIssueRelationRelatedByLinkedIssueIds")
     * @ORM\JoinColumn(name="linked_issue_id", referencedColumnName="id")
     */
    protected $eziIssueRelatedByLinkedIssueId;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssueRelation
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of issue_id.
     *
     * @param integer $issue_id
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssueRelation
     */
    public function setIssueId($issue_id)
    {
        $this->issue_id = $issue_id;

        return $this;
    }

    /**
     * Get the value of issue_id.
     *
     * @return integer
     */
    public function getIssueId()
    {
        return $this->issue_id;
    }

    /**
     * Set the value of linked_issue_id.
     *
     * @param integer $linked_issue_id
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssueRelation
     */
    public function setLinkedIssueId($linked_issue_id)
    {
        $this->linked_issue_id = $linked_issue_id;

        return $this;
    }

    /**
     * Get the value of linked_issue_id.
     *
     * @return integer
     */
    public function getLinkedIssueId()
    {
        return $this->linked_issue_id;
    }

    /**
     * Set EziIssue entity related by `issue_id` (many to one).
     *
     * @param \Ezi\Bundle\IssueBundle\Entity\EziIssue $eziIssue
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssueRelation
     */
    public function setEziIssueRelatedByIssueId(EziIssue $eziIssue = null)
    {
        $this->eziIssueRelatedByIssueId = $eziIssue;

        return $this;
    }

    /**
     * Get EziIssue entity related by `issue_id` (many to one).
     *
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssue
     */
    public function getEziIssueRelatedByIssueId()
    {
        return $this->eziIssueRelatedByIssueId;
    }

    /**
     * Set EziIssue entity related by `linked_issue_id` (many to one).
     *
     * @param \Ezi\Bundle\IssueBundle\Entity\EziIssue $eziIssue
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssueRelation
     */
    public function setEziIssueRelatedByLinkedIssueId(EziIssue $eziIssue = null)
    {
        $this->eziIssueRelatedByLinkedIssueId = $eziIssue;

        return $this;
    }

    /**
     * Get EziIssue entity related by `linked_issue_id` (many to one).
     *
     * @return \Ezi\Bundle\IssueBundle\Entity\EziIssue
     */
    public function getEziIssueRelatedByLinkedIssueId()
    {
        return $this->eziIssueRelatedByLinkedIssueId;
    }

    public function __sleep()
    {
        return array('id', 'issue_id', 'linked_issue_id');
    }
}