<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.5-dev (doctrine2-annotation) on 2015-01-15 07:46:49.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Ezi\Bundle\IssueBundle\Ezi\Bundle\IssueBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Ezi\Bundle\IssueBundle\Ezi\Bundle\IssueBundle\Entity\EziIssueCollaborator
 *
 * @ORM\Entity()
 * @ORM\Table(name="ezi_issue_collaborators", indexes={@ORM\Index(name="index2", columns={"user_id"}), @ORM\Index(name="index3", columns={"issue_id"})})
 */
class EziIssueCollaborator
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $user_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $issue_id;

    /**
     * @ORM\ManyToOne(targetEntity="EziIssue", inversedBy="eziIssueCollaborators")
     * @ORM\JoinColumn(name="issue_id", referencedColumnName="id", nullable=true)
     */
    protected $eziIssue;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Ezi\Bundle\IssueBundle\Ezi\Bundle\IssueBundle\Entity\EziIssueCollaborator
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of user_id.
     *
     * @param integer $user_id
     * @return \Ezi\Bundle\IssueBundle\Ezi\Bundle\IssueBundle\Entity\EziIssueCollaborator
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * Get the value of user_id.
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Set the value of issue_id.
     *
     * @param integer $issue_id
     * @return \Ezi\Bundle\IssueBundle\Ezi\Bundle\IssueBundle\Entity\EziIssueCollaborator
     */
    public function setIssueId($issue_id)
    {
        $this->issue_id = $issue_id;

        return $this;
    }

    /**
     * Get the value of issue_id.
     *
     * @return integer
     */
    public function getIssueId()
    {
        return $this->issue_id;
    }

    /**
     * Set EziIssue entity (many to one).
     *
     * @param \Ezi\Bundle\IssueBundle\Ezi\Bundle\IssueBundle\Entity\EziIssue $eziIssue
     * @return \Ezi\Bundle\IssueBundle\Ezi\Bundle\IssueBundle\Entity\EziIssueCollaborator
     */
    public function setEziIssue(EziIssue $eziIssue = null)
    {
        $this->eziIssue = $eziIssue;

        return $this;
    }

    /**
     * Get EziIssue entity (many to one).
     *
     * @return \Ezi\Bundle\IssueBundle\Ezi\Bundle\IssueBundle\Entity\EziIssue
     */
    public function getEziIssue()
    {
        return $this->eziIssue;
    }

    public function __sleep()
    {
        return array('id', 'user_id', 'issue_id');
    }
}